### ISSUE TITLE
Failed parsing in SMART impressions

### ISSUE THREAD

**Issue by matthieumontaigu** [artefactory/artefact.connectors#59]
```
[12:53:10] [INFO] [dku.utils]  -   File "/usr/local/lib/python2.7/dist-packages/artefact/utils/consume_parser.py", line 65, in timeout_handler
[12:53:10] [INFO] [dku.utils]  -     raise ConsumeTimeoutException("Timed out parsing line {0}".format(line))
[12:53:10] [INFO] [dku.utils]  - UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 19: ordinal not in range(128)
[12:53:10] [INFO] [dku.utils]  - 
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:166)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:207)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:125)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:70)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:313)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.rdd.RDD.iterator(RDD.scala:277)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.scheduler.Task.run(Task.scala:89)
[12:53:10] [INFO] [dku.utils]  -    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
[12:53:10] [INFO] [dku.utils]  -    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:53:10] [INFO] [dku.utils]  -    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:53:10] [INFO] [dku.utils]  -    ... 1 more
```

**Comment by d-tw** [comment]
http://analysis.artefact.is:8000/projects/ORANGEDATALAKE/jobs/Build_smart_impressions_logs_parsed_2016-10-23T18-54-24.186/

**Comment by d-tw** [comment]
@Declin Any updates?

**Comment by Declin** [comment]
@d-tw I think that the problem is solved. Tried on a sample and everything went well. I launched the job with the updates on the full table.

Plus: i add put lines that are failing into a dataset named : "smart_impressions_logs_parsed_failed"

Hope it will work on all logs :)

**Comment by Declin** [comment]
It worked! Here is the solution that will be usefull for other cases :

```python
def parse(row):
    from artefact.connectors.smart.impressions.line import Line
    
    try:
        clean_line = row.line.encode('ascii', 'replace').replace('?', '§')
        parsed_lines = Line.parse(clean_line)
        return parsed_lines
    except Exception as e:
        return [{'error': repr(e), 'source': row.line}]
```
